Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:13<00:13, 13.02s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:19<00:00,  8.89s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:19<00:00,  9.51s/it]
You shouldn't move a model that is dispatched using accelerate hooks.
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 171, in <module>
    main()
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 167, in main
    acc = eval_model(model.to("cuda"), tok, dataset, f"{args['test_dir']}_{args['test_file']}", args["model_name_or_path"], n = args['n'], lang = lang)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 122, in eval_model
    inputs = tokenizer(prompt_template(batch, lang, n), return_tensors = "pt").to(model.get_device())
                                                                                  ^^^^^^^^^^^^^^^^
  File "/home/khalevy/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MistralForCausalLM' object has no attribute 'get_device'. Did you mean: 'get_decoder'?
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:07<00:07,  7.09s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:10<00:00,  4.86s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:10<00:00,  5.19s/it]
You shouldn't move a model that is dispatched using accelerate hooks.
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 171, in <module>
    main()
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 167, in main
    acc = eval_model(model.to("cuda"), tok, dataset, f"{args['test_dir']}_{args['test_file']}", args["model_name_or_path"], n = args['n'], lang = lang)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 122, in eval_model
    inputs = tokenizer(prompt_template(batch, lang, n), return_tensors = "pt").to(model.get_device())
                                                                                  ^^^^^^^^^^^^^^^^
  File "/home/khalevy/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MistralForCausalLM' object has no attribute 'get_device'. Did you mean: 'get_decoder'?
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:06<00:06,  6.50s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:09<00:00,  4.43s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:09<00:00,  4.74s/it]
You shouldn't move a model that is dispatched using accelerate hooks.
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 171, in <module>
    main()
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 167, in main
    acc = eval_model(model.to("cuda"), tok, dataset, f"{args['test_dir']}_{args['test_file']}", args["model_name_or_path"], n = args['n'], lang = lang)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khalevy/Multilingual-Fig-QA/run_llm_baselines.py", line 122, in eval_model
    inputs = tokenizer(prompt_template(batch, lang, n), return_tensors = "pt").to("cuda")
                                                                                  ^^^^^^^^
  File "/home/khalevy/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MistralForCausalLM' object has no attribute 'get_device'. Did you mean: 'get_decoder'?
